using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hardwhat.Models;

namespace Hardwhat.Exporters
{

    public class HtmlExporter
    {

        public string Export(HardwareReport r)
        {

            var sb = new StringBuilder();

            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang='en-US'>");
            sb.AppendLine("<head>");
            sb.AppendLine("<meta charset='UTF-8' />");
            sb.AppendLine("<meta name='viewport' content='width=device-width, initial-scale=1' />");
            sb.AppendLine("<title>Hardware Information Detection Report</title>");
            sb.AppendLine(Styles);
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("");
            sb.AppendLine("<div class='app'>");

            sb.AppendLine(SidebarHtml);
            sb.AppendLine("<div class='divider' aria-hidden='true'></div>");
            sb.AppendLine("<main class='main'>");

            sb.AppendLine("  <h1 class='report-title'>Hardware Information Detection Report</h1>");
            sb.AppendLine("  <h3 class='report-time'>Generated Time: " + DateTime.Now.ToString("yyyy.MM.dd HH:mm:ss") + "</h3>");

            AppendOsSection(sb, r);
            AppendCpuSection(sb, r);
            AppendGpuSection(sb, r);
            AppendMemSection(sb, r);
            AppendDiskSection(sb, r);
            AppendMbSection(sb, r);
            AppendNetSection(sb, r);
            AppendAudioSection(sb, r);

            sb.AppendLine("  <footer class='report-footer'>");
            sb.AppendLine("    <p>This report was automatically generated by <strong>Hardwhat</strong>.</p>");
            sb.AppendLine("    <p><a href='https://github.com/Easzzz/Hardwhat' target='_blank' rel='noopener'>Hardwhat on GitHub</a></p>");
            sb.AppendLine("  </footer>");

            sb.AppendLine("</main>");
            sb.AppendLine("</div>");    // <div class='app'> 的结束
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");

            return sb.ToString();
        }



        private static void Title(StringBuilder sb, string id, string text)
        {
            sb.Append("  <h2 class='section-title' id='")
              .Append(id).Append("'>")
              .Append(HtmlEscape(text))
              .AppendLine("</h2>");
        }

        private static void Pair(StringBuilder sb, string key, string value)
        {
            sb.Append("    <span class='k'>").Append(HtmlEscape(key)).AppendLine("</span>");
            sb.Append("    <span class='v").Append("'>").Append(HtmlEscape(value)).AppendLine("</span>");
        }

        private static void BeginCard(StringBuilder sb)
        {
            sb.AppendLine("  <div class='card'>");
        }

        private static void EndCard(StringBuilder sb)
        {
            sb.AppendLine("  </div>");
        }

        private static void AppendOsSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "os", "Operating System");

            BeginCard(sb);
            Pair(sb, "Manufacturer", r.OsManufacturer);
            Pair(sb, "Caption", r.OsCaption);
            Pair(sb, "Version", r.OsVersion);
            Pair(sb, "Architecture", r.OsArchitecture);
            Pair(sb, "Build Number", r.OsBuildNumber);
            EndCard(sb);
        }

        private static void AppendCpuSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "cpu", "CPU");

            BeginCard(sb);
            Pair(sb, "Model", r.CpuModel);
            Pair(sb, "Cores", r.CpuCores);
            Pair(sb, "Threads", r.CpuLogicalProcessors);
            Pair(sb, "Max Clock Speed", r.CpuMaxClockSpeed);
            Pair(sb, "Socket", r.CpuSocket);
            Pair(sb, "Manufacturer", r.CpuManufacturer);
            EndCard(sb);
        }

        private static void AppendGpuSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "gpu", "GPU");

            int n = MaxCount(r.GpuNames, r.GpuMemories, r.GpuDrivers, r.GpuManufacturers);
            for (int i = 0; i < n; i++)
            {
                BeginCard(sb);
                Pair(sb, "#", $"GPU #{i}");
                Pair(sb, "Name", At(r.GpuNames, i));
                Pair(sb, "Memory", At(r.GpuMemories, i));
                Pair(sb, "Driver", At(r.GpuDrivers, i));
                Pair(sb, "Manufacturer", At(r.GpuManufacturers, i));
                EndCard(sb);
            }
        }

        private static void AppendMemSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "mem", "Memory");

            BeginCard(sb);
            Pair(sb, "Total Capacity", TotalCapacity(r.MemCapacities));
            Pair(sb, "Configured Speed", MinSpeed(r.MemSpeeds));
            EndCard(sb);

            int n = r.MemManufacturers.Count;
            for (int i = 0; i < n; i++)
            {
                BeginCard(sb);
                Pair(sb, "#", $"Slot #{i}");
                Pair(sb, "Manufacturer", At(r.MemManufacturers, i));
                Pair(sb, "Capacity", At(r.MemCapacities, i));
                Pair(sb, "MemSpeed", At(r.MemSpeeds, i));
                EndCard(sb);
            }
        }

        private static void AppendDiskSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "disk", "Disk");

            int n = MaxCount(r.DiskModels, r.DiskCapacities, r.DiskTypes, r.DiskInterfaces);
            for (int i = 0; i < n; i++)
            {
                BeginCard(sb);
                Pair(sb, "#", $"Disk #{i}");
                Pair(sb, "Model", At(r.DiskModels, i));
                Pair(sb, "Capacity", At(r.DiskCapacities, i));
                Pair(sb, "Type", At(r.DiskTypes, i));
                Pair(sb, "Interface", At(r.DiskInterfaces, i));
                EndCard(sb);
            }
        }

        private static void AppendMbSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "mb", "Mainboard");

            BeginCard(sb);
            Pair(sb, "Manufacturer", r.MbManufacturer);
            Pair(sb, "Product", r.MbProduct);
            Pair(sb, "Version", r.MbVersion);
            Pair(sb, "Serial Number", r.MbSerialNumber);
            EndCard(sb);
        }

        private static void AppendNetSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "net", "Network");

            int n = MaxCount(r.NetNames, r.NetManufacturers, r.NetMacAddresses,
                             r.NetSpeeds, r.NetTypes);
            for (int i = 0; i < n; i++)
            {
                BeginCard(sb);
                Pair(sb, "#", $"Network Adapter #{i}");
                Pair(sb, "Name", At(r.NetNames, i));
                Pair(sb, "Manufacturer", At(r.NetManufacturers, i));
                Pair(sb, "MAC Address", At(r.NetMacAddresses, i));
                Pair(sb, "Speed", At(r.NetSpeeds, i));
                Pair(sb, "Type", At(r.NetTypes, i));
                EndCard(sb);
            }
        }

        private static void AppendAudioSection(StringBuilder sb, HardwareReport r)
        {
            Title(sb, "audio", "Audio");

            int n = MaxCount(r.AudioNames, r.AudioManufacturers);
            for (int i = 0; i < n; i++)
            {
                BeginCard(sb);
                Pair(sb, "#", $"Audio Adapter #{i}");
                Pair(sb, "Name", At(r.AudioNames, i));
                Pair(sb, "Manufacturer", At(r.AudioManufacturers, i));
                EndCard(sb);
            }
        }



        private static string At(List<string> list, int i)
        {
            if (list == null || i < 0 || i >= list.Count) return "";
            return list[i] ?? "";
        }


        private static int MaxCount(params List<string>[] lists)
        {
            int max = 0;
            if (lists == null) return 0;
            foreach (var l in lists)
                if (l != null && l.Count > max) max = l.Count;
            return max;
        }

        private static string MinSpeed(List<string> list)
        {
            if (list == null || list.Count == 0) return "";

            int min = int.MaxValue;
            string result = "";

            foreach (string speed in list)
            {
                if (string.IsNullOrEmpty(speed)) continue;

                string[] parts = speed.Split(' ');
                if (parts.Length < 2) continue;

                int v;
                if (!int.TryParse(parts[0], out v)) continue;

                if (v < min)
                {
                    min = v;
                    result = speed;
                }
            }

            return result;
        }

        // 把 "8 GB" 之类的容量字符串求和，输出如 "32 GB (4 × 8 GB)"
        private static string TotalCapacity(List<string> capacities)
        {
            if (capacities == null || capacities.Count == 0) return "";

            double sum = 0;
            string unit = null;
            bool allOk = true;

            foreach (var c in capacities)
            {
                if (string.IsNullOrEmpty(c)) { allOk = false; break; }
                var parts = c.Split(' ');
                double v;
                if (parts.Length < 2 || !double.TryParse(parts[0], out v))
                {
                    allOk = false; break;
                }
                string u = parts[1].ToUpperInvariant();
                if (unit == null) unit = parts[1];
                else if (!string.Equals(unit, parts[1], StringComparison.OrdinalIgnoreCase))
                {
                    allOk = false; break;
                }
                sum += v;
            }

            if (!allOk) return string.Join(" + ", capacities);

            return string.Format("{0:0.##} {1} ({2} × {3} {1})",
                sum, unit, capacities.Count, capacities[0].Split(' ')[0]);
        }


        // 处理转义
        private static string HtmlEscape(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            var sb = new StringBuilder(s.Length + 8); // 预留 8 字节
            foreach (char c in s)
            {
                switch (c)
                {
                    case '&': sb.Append("&amp;"); break;
                    case '<': sb.Append("&lt;"); break;
                    case '>': sb.Append("&gt;"); break;
                    case '"': sb.Append("&quot;"); break;
                    case '\'': sb.Append("&#39;"); break;
                    default: sb.Append(c); break;
                }
            }
            return sb.ToString();
        }

        // @ 用单引号不用转义  
        private const string Styles = @"
            <style>
                :root
                {
                    --bg:#0F1117; --sidebar-top:#181C26; --sidebar-bottom:#0F1117;
                    --card:#181C26; --card-border:#2E3548;
                    --hover:#282F40; --hover-border:#3E4862;
                    --pressed:#333843; --pressed-border:#495165;
                    --text:#E2E6ED; --label:#8A90A2;
                    --icon:#8A90A2; --icon-hover:#E2E6ED; --icon-pressed:#FFFFFF;
                    --scroll-track:#181C26; --scroll-thumb:#282F40; --scroll-thumb-bd:#8A90A2;
                }

                *, *::before, *::after { box-sizing: border-box; }

                html, body { height: 100%; margin: 0; }

                body
                {
                    background: var(--bg); color: var(--text);
                    font-family: 'Microsoft Sans Serif','Segoe UI','PingFang SC','Microsoft YaHei',system-ui,sans-serif;
                    font-size: 14px; line-height: 1.45;
                    -webkit-font-smoothing: antialiased; overflow: hidden;
                }

                .app
                {
                    display: grid; grid-template-columns: 50px 4px 1fr; height: 100vh; overflow: hidden;
                }

                .sidebar
                {
                    display: flex; flex-direction: column; align-items: center; padding-top: 12px;
                    background: linear-gradient(180deg, var(--sidebar-top) 20.4%, var(--sidebar-bottom) 100%);
                }

                .icon-btn
                {
                width: 38px; height: 38px; margin: 3px 0 0 2px; padding: 0;
                border: 0; border-radius: 6px; background: transparent; color: var(--icon);
                cursor: pointer; display: inline-flex; align-items: center; justify-content: center;
                text-decoration: none; transition: background .15s ease, color .15s ease;
                -webkit-tap-highlight-color: transparent;
                }

                .icon-btn svg { width: 22px; height: 22px; display: block; }
                .icon-btn:hover  { background: var(--hover);   color: var(--icon-hover); }
                .icon-btn:active { background: var(--pressed); color: var(--icon-pressed); }
                .icon-btn:focus-visible { outline: 1px solid var(--hover-border); outline-offset: 1px; }

                .divider { background: linear-gradient(180deg, var(--hover) 20.4%, var(--sidebar-bottom) 100%); }

                .main { overflow-y: auto; overflow-x: hidden; padding: 4px 0 40px; scroll-behavior: smooth; }
                .main::-webkit-scrollbar { width: 8px; }
                .main::-webkit-scrollbar-track { background: var(--scroll-track); border-radius: 5px; }
                .main::-webkit-scrollbar-thumb { background: var(--scroll-thumb); border: 1px solid var(--scroll-thumb-bd); border-radius: 5px; }
                .main { scrollbar-width: auto; scrollbar-color: var(--scroll-thumb) var(--scroll-track); }
                

                .report-title
                {
                    margin: 10px 50px 4px 35px;
                    font-size: 34px;
                    font-weight: 700;
                    color: var(--text);
                }

                .report-time
                {
                    margin: 0 50px 4px 35px;
                    font-size: 16px;
                    font-weight: 500;
                    color: var(--text);
                }

                .report-footer
                {
                    margin: 0 50px 20px 30px;
                    padding-top: 20px;
                    border-top: 1px solid var(--card-border);
                    color: var(--label);
                    font-size: 13px;
                    line-height: 1.7;
                }

                .report-footer p { margin: 0; }

                .report-footer a
                {
                    color: #B6BBC8;
                    text-decoration: none;
                    border-bottom: 1px solid transparent;
                    transition: border-color .15s ease, color .15s ease;
                }

                .report-footer a:hover
                {
                    color: var(--text);
                    border-bottom-color: currentColor;
                }


                .section-title
                {
                    margin: 15px 0 10px 35px;
                    font-family: Consolas,'Cascadia Mono',ui-monospace,monospace;
                    font-size: 28px; font-weight: 700; color: var(--text);
                    letter-spacing: .01em; scroll-margin-top: 10px;
                }

                .card
                {
                    display: grid; grid-template-columns: 180px 1fr;
                    column-gap: 16px; row-gap: 10px;
                    margin: 0 50px 20px 30px; padding: 20px 25px;
                    background: var(--card); border: 1px solid var(--card-border); border-radius: 16px;
                }
                .card .k { color: var(--label); font-size: 14px; min-width: 0; }
                .card .v { color: var(--text);  font-size: 14px; min-width: 0;
                           word-break: break-word; overflow-wrap: anywhere; }


                @media (max-width: 720px)
                {
                    .app { grid-template-columns: 44px 3px 1fr; }
                    .icon-btn { width: 34px; height: 34px; margin-left: 1px; }
                    .icon-btn svg { width: 19px; height: 19px; }
                    .section-title { margin-left: 18px; font-size: 22px; }
                    .card { grid-template-columns: 1fr; row-gap: 2px; margin: 0 16px 16px 16px; padding: 16px 18px; }
                    .card .k { margin-top: 8px; font-size: 12px; letter-spacing: .02em; }
                    .card .v { font-size: 13.5px; }
                    .report-title { margin-left: 18px; font-size: 26px; }
                    .report-time { margin-left: 18px; font-size: 14px; }
                    .report-footer { margin: 0 16px 16px 16px; font-size: 12px; }
                }

            </style>
            ";

        private const string SidebarHtml = @"
            <aside class='sidebar' aria-label='Hardware categories'>

              <a class='icon-btn' href='#os' title='System' aria-label='System'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'> 
                  <path d='M12 17v4'/>
                  <path d='m14.305 7.53.923-.382'/>
                  <path d='m15.228 4.852-.923-.383'/>
                  <path d='m16.852 3.228-.383-.924'/>
                  <path d='m16.852 8.772-.383.923'/>
                  <path d='m19.148 3.228.383-.924'/>
                  <path d='m19.53 9.696-.382-.924'/>
                  <path d='m20.772 4.852.924-.383'/>
                  <path d='m20.772 7.148.924.383'/>
                  <path d='M22 13v2a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7'/>
                  <path d='M8 21h8'/>
                  <circle cx='18' cy='6' r='3'/>
                </svg>
              </a>

              <a class='icon-btn' href='#cpu' title='CPU' aria-label='CPU'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <path d='M12 20v2'/>
                  <path d='M12 2v2'/>
                  <path d='M17 20v2'/>
                  <path d='M17 2v2'/>
                  <path d='M2 12h2'/>
                  <path d='M2 17h2'/>
                  <path d='M2 7h2'/>
                  <path d='M20 12h2'/>
                  <path d='M20 17h2'/>
                  <path d='M20 7h2'/>
                  <path d='M7 20v2'/>
                  <path d='M7 2v2'/>
                  <rect x='4' y='4' width='16' height='16' rx='2'/>
                  <rect x='8' y='8' width='8' height='8' rx='1'/>
                </svg>
              </a>

              <a class='icon-btn' href='#gpu' title='GPU' aria-label='GPU'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <path d='M2 17h18a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2H2'/>
                  <path d='M2 21V3'/>
                  <path d='M7 17v3a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1v-3'/>
                  <circle cx='16' cy='11' r='2'/>
                  <circle cx='8' cy='11' r='2'/>
                </svg>
              </a>

              <a class='icon-btn' href='#mem' title='Memory' aria-label='Memory'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <path d='M12 12v-2'/>
                  <path d='M12 18v-2'/>
                  <path d='M16 12v-2'/>
                  <path d='M16 18v-2'/>
                  <path d='M2 11h1.5'/>
                  <path d='M20 18v-2'/>
                  <path d='M20.5 11H22'/>
                  <path d='M4 18v-2'/>
                  <path d='M8 12v-2'/>
                  <path d='M8 18v-2'/>
                  <rect x='2' y='6' width='20' height='10' rx='2'/>
                </svg>
              </a>

              <a class='icon-btn' href='#disk' title='Disk' aria-label='Disk'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <path d='M10 16h.01'/>
                  <path d='M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z'/>
                  <path d='M21.946 12.013H2.054'/>
                  <path d='M6 16h.01'/>
                </svg>
              </a>

              <a class='icon-btn' href='#mb' title='Mainboard' aria-label='Mainboard'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <rect width='18' height='18' x='3' y='3' rx='2'/>
                  <path d='M11 9h4a2 2 0 0 0 2-2V3'/>
                  <circle cx='9' cy='9' r='2'/>
                  <path d='M7 21v-4a2 2 0 0 1 2-2h4'/>
                  <circle cx='15' cy='15' r='2'/>
                </svg>
              </a>

              <a class='icon-btn' href='#net' title='Network' aria-label='Network'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <rect x='16' y='16' width='6' height='6' rx='1'/>
                  <rect x='2' y='16' width='6' height='6' rx='1'/>
                  <rect x='9' y='2' width='6' height='6' rx='1'/>
                  <path d='M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3'/>
                  <path d='M12 12V8'/>
                </svg>
              </a>

              <a class='icon-btn' href='#audio' title='Audio' aria-label='Audio'>
                <svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.2'
                     stroke-linecap='round' stroke-linejoin='round'>
                  <path d='M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z'/>
                  <path d='M16 9a5 5 0 0 1 0 6'/>
                  <path d='M19.364 18.364a9 9 0 0 0 0-12.728'/>
                </svg>
              </a>
            </aside>
            ";
    }
}